version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo installing...
    pre_build:
      commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install unit.js
    build:
      commands:
        - echo Build started on `date`
        - echo Compiling the Node.js code
        - node index.js
    post_build:
      commands:
        - echo Build completed on `date`
artifacts:
  files:
    - '**/*'